"""empty message

Revision ID: 8c22f2aceea2
Revises: 96ce7a69c9da
Create Date: 2022-10-15 23:21:08.322304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c22f2aceea2'
down_revision = '96ce7a69c9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favorite_character', 'characters', ['characters_id'], ['id'])
    op.create_foreign_key(None, 'favorite_character', 'users', ['users_id'], ['id'])
    op.create_foreign_key(None, 'favorite_planet', 'planets', ['planets_id'], ['id'])
    op.create_foreign_key(None, 'favorite_planet', 'users', ['users_id'], ['id'])
    op.drop_column('planets', 'created')
    op.drop_column('planets', 'population')
    op.drop_column('planets', 'surface_water')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('surface_water', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('planets', sa.Column('population', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('planets', sa.Column('created', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorite_planet', type_='foreignkey')
    op.drop_constraint(None, 'favorite_planet', type_='foreignkey')
    op.drop_constraint(None, 'favorite_character', type_='foreignkey')
    op.drop_constraint(None, 'favorite_character', type_='foreignkey')
    # ### end Alembic commands ###
