"""empty message

Revision ID: 96ce7a69c9da
Revises: fd7a06c45e2b
Create Date: 2022-10-15 22:44:48.415052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96ce7a69c9da'
down_revision = 'fd7a06c45e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'gender',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('characters', 'skin_color',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('characters', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('characters', 'mass',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'height',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('characters', 'birth_year')
    op.create_foreign_key(None, 'favorite_character', 'users', ['users_id'], ['id'])
    op.create_foreign_key(None, 'favorite_character', 'characters', ['characters_id'], ['id'])
    op.create_foreign_key(None, 'favorite_planet', 'planets', ['planets_id'], ['id'])
    op.create_foreign_key(None, 'favorite_planet', 'users', ['users_id'], ['id'])
    op.alter_column('planets', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'rotation_period',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'orbital_period',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'terrain',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planets', 'climate',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planets', 'surface_water',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'created',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'population',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planets', 'population',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'created',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'surface_water',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'climate',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('planets', 'terrain',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('planets', 'orbital_period',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'rotation_period',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'favorite_planet', type_='foreignkey')
    op.drop_constraint(None, 'favorite_planet', type_='foreignkey')
    op.drop_constraint(None, 'favorite_character', type_='foreignkey')
    op.drop_constraint(None, 'favorite_character', type_='foreignkey')
    op.add_column('characters', sa.Column('birth_year', mysql.VARCHAR(length=250), nullable=True))
    op.alter_column('characters', 'height',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'mass',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('characters', 'skin_color',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('characters', 'gender',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
