"""empty message

Revision ID: b77be8d67c9a
Revises: 8c22f2aceea2
Create Date: 2022-10-16 20:22:14.696349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b77be8d67c9a'
down_revision = '8c22f2aceea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'gender',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('characters', 'skin_color',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('characters', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('characters', 'mass',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'height',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'favorite_character', 'users', ['users_id'], ['id'])
    op.create_foreign_key(None, 'favorite_character', 'characters', ['characters_id'], ['id'])
    op.create_foreign_key(None, 'favorite_planet', 'users', ['users_id'], ['id'])
    op.create_foreign_key(None, 'favorite_planet', 'planets', ['planets_id'], ['id'])
    op.alter_column('planets', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'rotation_period',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'orbital_period',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planets', 'terrain',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('planets', 'climate',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=70),
               nullable=False)
    op.alter_column('users', 'lastname',
               existing_type=mysql.VARCHAR(length=70),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=mysql.VARCHAR(length=70),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=70),
               nullable=True)
    op.alter_column('planets', 'climate',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planets', 'terrain',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planets', 'orbital_period',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'rotation_period',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planets', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'favorite_planet', type_='foreignkey')
    op.drop_constraint(None, 'favorite_planet', type_='foreignkey')
    op.drop_constraint(None, 'favorite_character', type_='foreignkey')
    op.drop_constraint(None, 'favorite_character', type_='foreignkey')
    op.alter_column('characters', 'height',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'mass',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('characters', 'skin_color',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('characters', 'gender',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
